http:
  port: "![QALTuT+49+E=]"
  host: "![4hUzB55NXH0=]"
  path: "![WfC8Ikf4l5U=]"
  base_path: "![Vxf6VG2CgMI=]"
ocr_service:
  host: "![xO5s/+kE5XF+ecT3EwfXHzpcLv0zA+fQVadwElU7h4w=]"
  port: "![lQchelXWi0A=]"
  protocol: "![rt6HxmpxAyQ=]"
  base_path: "![fB+PP71ZnnM=]"
  client_id: "![YWtGwZrxWvIuLaz2+JUWlcP3ZEEk8YUELoprrFddvojX8gvPHqSVnQ==]"
  client_secret: "![FRb4/M3xHhzG6fLSe1gn9y7qpWZ5YT2B69CjOeVJkooM11zariPa8g==]"
sfdc_service:
  host: "![Xec7/Wyu6F2jIqnK1xmcpDADwZjxV6dRLxSQKt9frXmAUBGl3nXg+A==]"
  port: "![lQchelXWi0A=]"
  protocol: "![rt6HxmpxAyQ=]"
  base_path: "![fB+PP71ZnnM=]"
  client_id: "![kmABVwFJ4uaQWJlsh8UNS6CIJbw1II9YrLB2uLXzWXl98AEeOiCBNQ==]"
  client_secret: "![0/l0wh0dJWwzt+9sRn1rfR7PSzcnODiqv1UJ224o/5F602HD18gtcA==]"
