#%RAML 1.0
version: v1
title: Document Processing API

traits:
   client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

/docuement:
  post:
    is: [ client-id-required ]
    body:
      multipart/form-data:
        properties: 
          file1: 
            description: The file to translate to text 
            required: true 
            type: file 
            fileTypes: [ 'image/jpeg']              
          emailAddress:
            description: The email address of the submitter
            required: true
            type: string
            pattern: ^.+@.+\..+$
          keywords:
            description: "A ',' seperated list of words of phrases to match"
            type: string
            required: true
          language:
            description: The language code for the file - ISO 639-1 Language Codes
            required: true
            enum: [ 'en' ]
          contentType:
            description: The type of the document
            required: true
            type: string
          filename:
            description: The name of the document
            required: true
            type: string
          fileEncoding:
            description: The encoding type for the file
            enum: ['binary','base64']
            required: true

    responses: 
      201:
        description: Document submitted
        body: 
          application/json:
            example: { "status": "submitted"}
      204:
        description: Document not submitted
        body: 
          application/json:
            example: { "status": "no action"}